#ifndef FINGERPRINT_ERROR_CODE_H
#define FINGERPRINT_ERROR_CODE_H

enum FingerprintErrorCode {
    // Fingerprint Error Code (100-200)
    FAILED_TO_CONVERT_IMAGE_TO_FEATURE      = -100,
    FAILED_IMAGE_CONVERSION_ERROR           = -101,
    FAILED_TO_MAKE_FINGERPRINT_MODEL        = -102,
    FAILED_TO_CREATE_VERIFICATION_MODEL     = -103,
    FAILED_TO_DELETE_FINGERPRINT_MODEL      = -104,
    FAILED_TO_DELETE_ALL_FINGERPRINT_MODEL  = -105,
    FAILED_TO_GET_FINGERPRINT_MODEL_ID      = -106,
    FAILED_TO_CONNECT_FINGERPRINT_SENSOR    = -107,
    FAILED_TO_INTIALIZE_FINGERPRINT         = -108,
    
};

#endif
