// #####################################################################################################
// ###    This file is generated by Build and Continuous Integration scripts Github Action Runner    ###
// ###                         .github/workflows/build.yml for CI environment                        ###
// ###                    Changes will be overwritten on the next build                              ###
// #####################################################################################################
#ifndef VERSION_INFO_H
#define VERSION_INFO_H

#define CURRENT_FIRMWARE_VERSION GIT_REV
#define LAST_BUILD_FIRMWARE_VERSION "0.2.1"
#define LAST_FIRMWARE_VERSION_FILENAME "0_2_1"
#define LAST_COMMIT_HASH "065fad9"
#define LAST_BUILD_TIMESTAMP "2025-Mar-24-18:06:26"

#endif