// #####################################################################################################
// ###    This file is generated by Build and Continuous Integration scripts Github Action Runner    ###
// ###                         .github/workflows/build.yml for CI environment                        ###
// ###                    Changes will be overwritten on the next build                              ###
// #####################################################################################################
#ifndef VERSION_INFO_H
#define VERSION_INFO_H

#define CURRENT_FIRMWARE_VERSION GIT_REV
#define LAST_BUILD_FIRMWARE_VERSION "0.3.0"
#define LAST_FIRMWARE_VERSION_FILENAME "0_3_0"
#define LAST_COMMIT_HASH "83b3d52"
#define LAST_BUILD_TIMESTAMP "2025-May-30-08:40:31"

#endif